---

- name: Create ports directory
  shell: ftp -o - https://ftp.openbsd.org/pub/OpenBSD/6.0/ports.tar.gz | tar -C /usr -zxf -
  args:
    creates: /usr/ports/Makefile
  register: register_ftp_o_tar_C_zxf

- name: Add ssh key to known_hosts
  known_hosts:
    path: /etc/ssh/ssh_known_hosts
    state: present
    name: anoncvs.ca.openbsd.org
    key: "{{ item }}"
  with_file:
    - files/anoncvs.ca.openbsd.org

- name: Update ports tree
  # XXX the git repository, unofficially published at github.com, cannot be used
  # here because the repository does not have tags, but only HEAD. HEAD can only
  # be built on -current. To support git repository, one must convert a tagged
  # CVS branch to a git branch, and tag it.
  command: cvs -qd anoncvs@anoncvs.ca.openbsd.org:/cvs get -rOPENBSD_6_0 -P ports
  args:
    chdir: /usr
  when:
    - register_ftp_o_tar_C_zxf.changed

- name: Create symlink to dpb
  file:
    state: link
    src: /usr/ports/infrastructure/bin/dpb
    dest: /usr/local/bin/dpb

- name: Create symlink to proot
  file:
    state: link
    src: /usr/ports/infrastructure/bin/proot
    dest: /usr/local/bin/proot

# install X-related sets. without them, it is not possible to build packages
# that depends on X, i.e. java
- name: Install xbase
  shell: ftp -o - https://ftp.openbsd.org/pub/OpenBSD/6.0/amd64/xbase60.tgz | tar -C / -zxf -
  args:
    creates: /usr/X11R6/bin/xdm

- name: Install xfont
  shell: ftp -o - https://ftp.openbsd.org/pub/OpenBSD/6.0/amd64/xfont60.tgz | tar -C / -zxf -
  args:
    creates: /usr/X11R6/lib/X11/fonts/TTF/DejaVuSansMono.ttf

- name: Install xshare
  shell: ftp -o - https://ftp.openbsd.org/pub/OpenBSD/6.0/amd64/xshare60.tgz | tar -C / -zxf -
  args:
    creates: /usr/X11R6/bin/startx
