---
# tasks file for ansible-role-dpb

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

# Unset "nodev" mount(8) option if /usr/local is mounted with the option before
# creating chroot because, inside of chroot, device nodes must be created.
- name: Get mount option of /usr/local
  # translation:
  #
  # * get `mount(8)` output
  # * remove unnecessary lines starting with '#'
  # * select an entry with mount point == "/usr/local"
  # * remove everything other than options
  #
  # the result is "opt1,opt2"
  shell: "mount | grep -v '^#' | awk '{if ($3 == \"/usr/local\") { print $0 }}' | sed -e 's/^.*(//' -e 's/)$//' -e 's/[ ]//g'"
  register: register_mount_grep_awk
  changed_when: false

- set_fact:
    # by default, fstab(5) uses disk UUID, instead of device name. to set mount
    # option, disk UUID
    dpb_mount_device_uuid: "{{ ansible_mounts | selectattr('mount', 'equalto', '/usr/local') | map(attribute='device') | first }}"

- name: Set options for /usr/local in fstab(5)
  # XXX "state: mounted" does not work in OpenBSD. what the task does here is
  # removing "nodev" option from fstab(5). the next "Re-mount" task applies the
  # options.
  # "Error mounting /usr/local: mount_ffs: -o remount: option not supported"
  mount:
    state: present
    opts: "{{ register_mount_grep_awk.stdout.split(',') | reject('equalto', 'nodev') | join(',') }}"
    name: /usr/local
    fstype: ffs
    src: "{{ dpb_mount_device_uuid }}"
  register: mount_usr_local
  when:
    # run the task when /usr/local is mounted with "nodev"
    - register_mount_grep_awk.stdout.find('nodev') >= 0

- name: Re-mount /usr/local
  # '-u' does not change options other than one specified with "-o". other
  # options are left intact.
  command: mount -u -o dev /usr/local
  when:
    - register_mount_grep_awk.stdout.find('nodev') >= 0

- name: Get mount option of /usr/local
  # get the options again to make sure /usr/local is mounted without "nodev"
  shell: "mount | grep -v '^#' | awk '{if ($3 == \"/usr/local\") { print $0 }}' | sed -e 's/^.*(//' -e 's/)$//' -e 's/,[ ]/ /g'"
  register: register_mount_grep_awk
  changed_when: false

- assert:
    # this time, /usr/local should be mounted without "nodev"
    that:
      - register_mount_grep_awk.stdout.find('nodev') < 0

- name: Create dpb_conf_dir
  file:
    path: "{{ dpb_conf_dir }}"
    state: directory

- name: Create package list to build
  template:
    src: packages.dpb.j2
    dest: "{{ dpb_conf_file }}"

- name: Create proot.conf
  template:
    src: proot.conf.j2
    dest: "{{ dpb_proot_conf_file }}"

- name: Create chroot
  command: "proot -c {{ dpb_proot_conf_file }}"
  args:
    creates: "{{ dpb_proot_chroot }}/usr/ports/Makefile"

# dpb -P /etc/dpb/packages.dpb -B /usr/local/build
